# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: continuous-deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: package version to build / publish
        required: true
        type: string

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-packages:
    strategy:
      matrix:
        platform: [apple, linux, windows]
        architecture: [x64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.33.x
      - run: deno task build:package --version ${{ inputs.version }} --arch ${{ matrix.architecture }} --platform ${{ matrix.platform }}
      - uses: actions/upload-artifact@v3
        with:
          name: deno-npx-${{ matrix.platform }}-${{ matrix.architecture }}
          path: build/deno-npx-${{ matrix.platform }}-${{ matrix.architecture }}
  build-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.33.x
      - run: deno task build:main --version ${{ inputs.version }}
      - uses: actions/upload-artifact@v3
        with:
          name: deno-npx
          path: build/deno-npx
  publish-packages:
    needs: [build-packages, build-main]
    strategy:
      matrix:
        platform: [apple, linux, windows]
        architecture: [x64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: deno-npx-${{ matrix.platform }}-${{ matrix.architecture }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-main:
    needs: [build-packages, build-main]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: deno-npx
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
