# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: continuous-deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: package version to build / publish
        required: true
        type: string

jobs:
  build-packages:
    strategy:
      matrix:
        platform: [apple, linux, windows]
        architecture: [x64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.33.x
      - run: deno task build:package --version ${{ inputs.version }} --arch ${{ matrix.architecture }} --platform ${{ matrix.platform }}
      - uses: actions/upload-artifact@v3
        with:
          name: deno-npx-${{ matrix.platform }}-${{ matrix.architecture }}
          path: build/deno-npx-${{ matrix.platform }}-${{ matrix.architecture }}
  build-main:
    runs-on: ubuntu-latest
    needs: build-packages
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.33.x
      - run: deno task build:main --version ${{ inputs.version }}
      - uses: actions/upload-artifact@v3
        with:
          name: deno-npx
          path: build/deno-npx
